### ISSUE TITLE
app doesn't not start

### ISSUE THREAD

**Issue by raininja** [ramsaylanier/WordpressExpress#37]
[raijin@ishtar][~http/wordexpress/express_test/WordExpress]%npm run startdev

> wordpress-express@0.1.0 startdev /srv/http/wordexpress/express_test/WordExpress
> better-npm-run startdev

running better-npm-run in /srv/http/wordexpress/express_test/WordExpress
Executing script: startdev

to be executed: babel-node --debug ./dev.js
(node:7517) DeprecationWarning: node --debug is deprecated. Please use node --inspect instead.
Debugger listening on 127.0.0.1:5858
[15:01:08] [write-file-webpack-plugin] options { exitOnErrors: true,
  force: false,
  log: true,
  test: null,
  useHashIndex: true }
App is now running on http://localhost:3000

/srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Chunk.js:41
                throw new Error("Chunk.entry was removed. Use hasRuntime()");
                ^

Error: Chunk.entry was removed. Use hasRuntime()
    at Chunk.get entry [as entry] (/srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Chunk.js:41:9)
    at /srv/http/wordexpress/express_test/WordExpress/node_modules/extract-text-webpack-plugin/index.js:201:13
    at Array.filter (native)
    at Compilation.<anonymous> (/srv/http/wordexpress/express_test/WordExpress/node_modules/extract-text-webpack-plugin/index.js:200:37)
    at Compilation.applyPlugins0 (/srv/http/wordexpress/express_test/WordExpress/node_modules/tapable/lib/Tapable.js:68:14)
    at Compilation.seal (/srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Compilation.js:567:8)
    at /srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Compiler.js:493:16
    at /srv/http/wordexpress/express_test/WordExpress/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/srv/http/wordexpress/express_test/WordExpress/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wordpress-express@0.1.0 startdev: `better-npm-run startdev`
npm ERR! Exit status 1
npm ERR!

**Comment by richimgd** [comment]
I had the same issue, in package.json edit "extract-text-webpack-plugin": "^2.0.0-rc.3" and then run npm install again...

**Comment by peacechen** [comment]
See #38
